### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by minhchau273** [nhunghuynhthihong/tipping#1]
👍 Congratulation on finishing the Tip Calculator with the nice UI. Your app looks great.
#### Some small comments:
- Great job using the auto layout 💯 This is one of the hardest lesson in this Swift class.
- Good usage of the NSUserDefault. This is one of the methods to pass data between view controllers.
- Nice with the validation of percentages in `SettingViewController`.
- You shouldn't let the user enter invalid number, should you? I can enter bunch of leading zeros and many dots. I can also paste some text in the text field:  
  <img width="315" alt="screen shot 2016-06-26 at 5 52 14 pm" src="https://cloud.githubusercontent.com/assets/12395213/16361868/3f73c410-3bc8-11e6-9ccd-6d786f9d7d86.png">

**Comment by nhunghuynhthihong** [comment]
Hi Chau,
Thanks for your comments. I updated validation for Bill Amount value.
Regards,
Nhung
